# Use an official Maven image to build the Spring Boot application
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app/backend

# Copy the pom.xml and source code to the container
COPY pom.xml .
COPY src ./src

# Package the Spring Boot application
RUN mvn clean package -DskipTests

# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/backend/target/healthconnect-0.0.1-SNAPSHOT.jar /app/HealthConnectApplication.jar

# Expose the backend port
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app/HealthConnectApplication.jar"]
